name: emrys-real-e2e-tools

channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - bcftools=1.21
  - gatk4=4.6.1.0
  - gzip
  - openjdk=17
  - picard-slim=3.1.1
  - rseqc=5.0.4
  - samtools=1.19.2
  - star=2.7.11b
