#!/usr/bin/env python3
"""Validate repository documentation links, task cards, and Mermaid sources."""

from __future__ import annotations

import argparse
import re
import subprocess
from collections.abc import Iterable
from pathlib import Path
from urllib.parse import unquote


CARD_SECTIONS = (
    "Objective",
    "Why this exists",
    "Fixed decisions",
    "Blocked by",
    "Completion unblocks",
    "Prerequisites",
    "Required context",
    "Questions owned by this card",
    "In scope",
    "Out of scope",
    "Deliverables",
    "Acceptance evidence",
    "Canonical documentation updates",
    "Escalation conditions",
    "Completion record",
)
UNREFINED_SECTIONS = (
    "Proposal",
    "Why preserve it",
    "Settled boundaries",
    "Questions before refinement",
    "Promotion conditions",
)
CARD_STATUSES = frozenset(
    {"TODO", "IN_PROGRESS", "INTEGRATION_REVIEW", "COMPLETED"}
)
STARTED_CARD_STATUSES = frozenset(
    {"IN_PROGRESS", "INTEGRATION_REVIEW", "COMPLETED"}
)
EXTERNAL_SCHEMES = ("http://", "https://", "mailto:", "data:")
TASK_H1_PATTERN = re.compile(r"^([A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+) — .+$")
UNREFINED_STATE_PATTERN = re.compile(
    r"State: \[`UNREFINED` proposal\]\(README\.md\)\.(?: .+)?"
)


class DocumentationError(RuntimeError):
    """Raised when the documentation gate itself cannot run safely."""


def git_paths(root: Path, pattern: str) -> list[Path]:
    """Return tracked and untracked, non-ignored paths matching one pattern."""
    result = subprocess.run(
        [
            "git",
            "-C",
            str(root),
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            "--",
            pattern,
        ],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "no diagnostic"
        raise DocumentationError(f"could not inventory {pattern}: {detail}")
    return [root / value for value in result.stdout.splitlines()]


def repository_root(value: Path) -> Path:
    """Resolve and verify the exact root of one Git worktree."""
    try:
        root = value.resolve(strict=True)
    except OSError as exc:
        raise DocumentationError(f"repository path is unavailable: {value}: {exc}") from exc
    result = subprocess.run(
        ["git", "-C", str(root), "rev-parse", "--show-toplevel"],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "no diagnostic"
        raise DocumentationError(f"not a Git worktree: {root}: {detail}")
    actual = Path(result.stdout.strip()).resolve()
    if actual != root:
        raise DocumentationError(f"repository path is not the worktree root: {root}")
    return root


def anchors(document: Path) -> set[str]:
    """Return the GitHub-style anchors generated by one Markdown document."""
    counts: dict[str, int] = {}
    result: set[str] = set()
    for line in document.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^#{1,6}\s+(.+?)\s*#*\s*$", line)
        if not match:
            continue
        heading = re.sub(r"<[^>]*>", "", match.group(1)).lower()
        base = re.sub(r"[^\w\- ]", "", heading).replace(" ", "-")
        number = counts.get(base, 0)
        counts[base] = number + 1
        result.add(base if number == 0 else f"{base}-{number}")
    return result


def validate_links(
    root: Path,
    documents: Iterable[Path],
    problems: list[str],
) -> dict[Path, set[Path]]:
    """Validate local Markdown links and collect inbound references."""
    document_list = list(documents)
    document_anchors = {document: anchors(document) for document in document_list}
    inbound: dict[Path, set[Path]] = {}
    for document in document_list:
        text = document.read_text(encoding="utf-8")
        for raw_target in re.findall(r"\[[^\]]+\]\(([^)]+)\)", text):
            raw_target = raw_target.strip().strip("<>")
            if raw_target.startswith(EXTERNAL_SCHEMES):
                continue
            path_text, separator, fragment = raw_target.partition("#")
            path = (
                document
                if not path_text
                else (document.parent / unquote(path_text)).resolve()
            )
            if not path.exists():
                problems.append(
                    f"missing link: {document.relative_to(root)} -> {raw_target}"
                )
                continue
            inbound.setdefault(path, set()).add(document)
            if separator and path.suffix == ".md":
                fragment = unquote(fragment).lower()
                if fragment not in document_anchors.get(path, set()):
                    problems.append(
                        f"missing anchor: {document.relative_to(root)} -> {raw_target}"
                    )
    return inbound


def validate_cards(
    root: Path,
    inbound: dict[Path, set[Path]],
    problems: list[str],
) -> int:
    """Validate task-card structure, links, and direct dependency semantics."""
    task_root = root / "docs" / "tasks"
    required_readmes = {
        task_root / "README.md",
        task_root / "TODO" / "README.md",
        task_root / "IN_PROGRESS" / "README.md",
        task_root / "INTEGRATION_REVIEW" / "README.md",
        task_root / "COMPLETED" / "README.md",
        task_root / "UNREFINED" / "README.md",
    }
    for readme in sorted(required_readmes):
        if not readme.is_file():
            problems.append(f"missing task-registry README: {readme.relative_to(root)}")

    cards: dict[str, Path] = {}
    blocked: dict[str, set[str]] = {}
    unblocks: dict[str, dict[str, str]] = {}
    proposals: dict[str, Path] = {}
    structurally_valid_cards: set[str] = set()
    for path in sorted(task_root.rglob("*.md")):
        if path in required_readmes:
            continue
        if path.parent == task_root / "UNREFINED":
            text = path.read_text(encoding="utf-8")
            titles = re.findall(r"^#\s+(.+)$", text, flags=re.MULTILINE)
            title = (
                TASK_H1_PATTERN.fullmatch(titles[0])
                if len(titles) == 1
                else None
            )
            if not title:
                problems.append(f"invalid proposal H1: {path.relative_to(root)}")
                continue
            proposal_id = title.group(1)
            if not path.name.startswith(f"{proposal_id}-"):
                problems.append(
                    f"proposal ID/filename mismatch: {path.relative_to(root)}"
                )
            if proposal_id in proposals or proposal_id in cards:
                problems.append(f"duplicate proposal ID: {proposal_id}")
            proposals[proposal_id] = path

            state_lines = re.findall(r"^State: .+$", text, flags=re.MULTILINE)
            if len(state_lines) != 1 or not UNREFINED_STATE_PATTERN.fullmatch(
                state_lines[0]
            ):
                problems.append(
                    "invalid proposal state declaration: "
                    f"{path.relative_to(root)}"
                )

            headings = re.findall(r"^##\s+(.+)$", text, flags=re.MULTILINE)
            prior_index = -1
            valid_heading_order = True
            for required_heading in UNREFINED_SECTIONS:
                if headings.count(required_heading) != 1:
                    valid_heading_order = False
                    break
                heading_index = headings.index(required_heading)
                if heading_index <= prior_index:
                    valid_heading_order = False
                    break
                prior_index = heading_index
            if not valid_heading_order:
                problems.append(
                    f"proposal heading order/count: {path.relative_to(root)}"
                )

            actionable_heading = next(
                (heading for heading in headings if heading in CARD_SECTIONS),
                None,
            )
            if actionable_heading is not None:
                problems.append(
                    "actionable card heading in proposal: "
                    f"{path.relative_to(root)} -> {actionable_heading}"
                )
            if re.search(
                r"^- \[[A-Z0-9-]+\]\([^)]+\.md\) — "
                r"(?:Required|Fully|Partially): .+$",
                text,
                flags=re.MULTILINE,
            ):
                problems.append(
                    f"dependency edge in proposal: {path.relative_to(root)}"
                )
            continue
        if path.parent.name not in CARD_STATUSES or path.parent.parent != task_root:
            problems.append(f"invalid card location: {path.relative_to(root)}")
            continue
        text = path.read_text(encoding="utf-8")
        titles = re.findall(r"^#\s+(.+)$", text, flags=re.MULTILINE)
        title = (
            TASK_H1_PATTERN.fullmatch(titles[0])
            if len(titles) == 1
            else None
        )
        if not title:
            problems.append(f"invalid card H1: {path.relative_to(root)}")
            continue
        card_id = title.group(1)
        if not path.name.startswith(f"{card_id}-"):
            problems.append(f"card ID/filename mismatch: {path.relative_to(root)}")
        if card_id in cards:
            problems.append(f"duplicate card ID: {card_id}")
        cards[card_id] = path
        headings = re.findall(r"^##\s+(.+)$", text, flags=re.MULTILINE)
        if headings != list(CARD_SECTIONS):
            problems.append(f"card heading order/count: {path.relative_to(root)}")
        else:
            structurally_valid_cards.add(card_id)

    required_pattern = re.compile(
        r"^- \[([A-Z0-9-]+)\]\([^)]+\.md\) — Required: .+$"
    )
    unblock_pattern = re.compile(
        r"^- \[([A-Z0-9-]+)\]\([^)]+\.md\) — (Fully|Partially): .+$"
    )
    for card_id, path in cards.items():
        if card_id not in structurally_valid_cards:
            blocked[card_id] = set()
            unblocks[card_id] = {}
            continue
        text = path.read_text(encoding="utf-8")
        blocked_text = text.split("## Blocked by\n", 1)[1].split(
            "\n## Completion unblocks", 1
        )[0]
        unblocks_text = text.split("## Completion unblocks\n", 1)[1].split(
            "\n## Prerequisites", 1
        )[0]
        blocked_lines = [line for line in blocked_text.splitlines() if line.strip()]
        unblock_lines = [line for line in unblocks_text.splitlines() if line.strip()]
        if blocked_lines != ["- None."] and not all(
            required_pattern.fullmatch(line) for line in blocked_lines
        ):
            problems.append(f"invalid Blocked by syntax: {path.relative_to(root)}")
        if unblock_lines != ["- None."] and not all(
            unblock_pattern.fullmatch(line) for line in unblock_lines
        ):
            problems.append(
                f"invalid Completion unblocks syntax: {path.relative_to(root)}"
            )
        blocked[card_id] = set(re.findall(r"\[([A-Z0-9-]+)\]\(", blocked_text))
        unblocks[card_id] = {
            target: mode
            for target, mode in re.findall(
                r"\[([A-Z0-9-]+)\]\([^)]+\) — (Fully|Partially):",
                unblocks_text,
            )
        }
        for label, target in re.findall(r"\[([A-Z0-9-]+)\]\(([^)]+\.md)\)", text):
            resolved = (path.parent / target).resolve()
            if resolved.parent.parent == task_root and not resolved.name.startswith(
                f"{label}-"
            ):
                problems.append(
                    f"card-link label/target mismatch: {path.relative_to(root)} "
                    f"{label} -> {target}"
                )

    for target, sources in blocked.items():
        for source in sources:
            if source not in cards:
                problems.append(f"unknown blocker: {target} <- {source}")
            elif target not in unblocks[source]:
                problems.append(f"missing reciprocal unblock: {source} -> {target}")
            if source == target:
                problems.append(f"self dependency: {target}")
    for source, targets in unblocks.items():
        for target, mode in targets.items():
            if target not in cards:
                problems.append(f"unknown unblock target: {source} -> {target}")
            elif mode == "Fully" and blocked[target] != {source}:
                problems.append(f"invalid Fully relationship: {source} -> {target}")

    visiting: list[str] = []
    visited: set[str] = set()

    def visit(card_id: str) -> None:
        if card_id in visiting:
            problems.append("dependency cycle: " + " -> ".join(visiting + [card_id]))
            return
        if card_id in visited:
            return
        visiting.append(card_id)
        for dependency in blocked.get(card_id, set()):
            if dependency in cards:
                visit(dependency)
        visiting.pop()
        visited.add(card_id)

    for card_id in cards:
        visit(card_id)

    for card_id, path in cards.items():
        if not (inbound.get(path, set()) - {path}):
            problems.append(f"orphan task card: {path.relative_to(root)}")
        if path.parent.name in STARTED_CARD_STATUSES:
            for dependency in blocked[card_id]:
                if dependency in cards and cards[dependency].parent.name != "COMPLETED":
                    problems.append(
                        "active/completed card has incomplete blocker: "
                        f"{card_id} <- {dependency}"
                    )
    return len(cards)


def validate_diagrams(
    root: Path,
    diagrams: Iterable[Path],
    inbound: dict[Path, set[Path]],
    problems: list[str],
) -> int:
    """Validate Mermaid source shape and inbound references."""
    diagram_list = list(diagrams)
    for diagram in diagram_list:
        text = diagram.read_text(encoding="utf-8")
        meaningful = [line.strip() for line in text.splitlines() if line.strip()]
        if not meaningful or not re.fullmatch(
            r"flowchart (LR|RL|TB|BT|TD)", meaningful[0]
        ):
            problems.append(f"invalid Mermaid declaration: {diagram.relative_to(root)}")
        if "```" in text:
            problems.append(f"Markdown fence in Mermaid source: {diagram.relative_to(root)}")
        if not (inbound.get(diagram, set()) - {diagram}):
            problems.append(f"orphan Mermaid source: {diagram.relative_to(root)}")
    return len(diagram_list)


def validate(root: Path) -> tuple[int, int, int]:
    """Run the complete structural documentation gate."""
    documents = git_paths(root, "*.md")
    diagrams = git_paths(root, "*.mmd")
    problems: list[str] = []
    inbound = validate_links(root, documents, problems)
    card_count = validate_cards(root, inbound, problems)
    diagram_count = validate_diagrams(root, diagrams, inbound, problems)
    if problems:
        raise DocumentationError("Documentation gate failures:\n" + "\n".join(problems))
    return len(documents), card_count, diagram_count


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate NORAD documentation links, task cards, and diagrams."
    )
    parser.add_argument(
        "--repo",
        required=True,
        type=Path,
        help="exact Git worktree root to validate",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    try:
        root = repository_root(args.repo)
        document_count, card_count, diagram_count = validate(root)
    except DocumentationError as exc:
        raise SystemExit(f"ERROR: {exc}") from exc
    print(
        f"PASS documentation structure ({document_count} Markdown documents, "
        f"{card_count} task cards, {diagram_count} Mermaid sources)"
    )


if __name__ == "__main__":
    main()
