#!/usr/bin/env python3
"""Validate repository documentation links, task cards, and Mermaid sources."""

from __future__ import annotations

import argparse
import re
import subprocess
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import unquote


CARD_SECTIONS = (
    "Objective",
    "Why this exists",
    "Fixed decisions",
    "Blocked by",
    "Completion unblocks",
    "Prerequisites",
    "Required context",
    "Questions owned by this card",
    "In scope",
    "Out of scope",
    "Deliverables",
    "Acceptance evidence",
    "Canonical documentation updates",
    "Escalation conditions",
    "Completion record",
)
STABLE_CARD_SECTIONS = (
    "Objective",
    "Why this exists",
    "Fixed decisions",
    "Blocked by",
    "Prerequisites",
    "Required context",
    "Questions owned by this card",
    "In scope",
    "Out of scope",
    "Deliverables",
    "Acceptance evidence",
    "Documentation impact triggers",
    "Escalation conditions",
    "Completion record",
)
UNREFINED_SECTIONS = (
    "Proposal",
    "Why preserve it",
    "Settled boundaries",
    "Questions before refinement",
    "Promotion conditions",
)
CARD_STATUSES = frozenset(
    {"TODO", "IN_PROGRESS", "INTEGRATION_REVIEW", "COMPLETED"}
)
STARTED_CARD_STATUSES = frozenset(
    {"IN_PROGRESS", "INTEGRATION_REVIEW", "COMPLETED"}
)
CARD_STATES = frozenset({"planned", "review", "completed", "retired"})
LEGACY_STATE_BY_STATUS = {
    "TODO": "planned",
    "IN_PROGRESS": "planned",
    "INTEGRATION_REVIEW": "review",
    "COMPLETED": "completed",
}
EXTERNAL_SCHEMES = ("http://", "https://", "mailto:", "data:")
TASK_H1_PATTERN = re.compile(r"^([A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+) — .+$")
CARD_STATE_PATTERN = re.compile(r"State: (planned|review|completed|retired)")
UNREFINED_STATE_PATTERN = re.compile(
    r"State: \[`UNREFINED` proposal\]\(README\.md\)\.(?: .+)?"
)


class DocumentationError(RuntimeError):
    """Raised when the documentation gate itself cannot run safely."""


@dataclass(frozen=True)
class TaskCard:
    """One parsed actionable card from either registry generation."""

    card_id: str
    path: Path
    state: str
    explicit_state: bool
    stable_schema: bool
    blockers: frozenset[str]
    unblocks: dict[str, str]


def git_paths(root: Path, pattern: str) -> list[Path]:
    """Return tracked and untracked, non-ignored paths matching one pattern."""
    result = subprocess.run(
        [
            "git",
            "-C",
            str(root),
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            "--",
            pattern,
        ],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "no diagnostic"
        raise DocumentationError(f"could not inventory {pattern}: {detail}")
    return [root / value for value in result.stdout.splitlines()]


def repository_root(value: Path) -> Path:
    """Resolve and verify the exact root of one Git worktree."""
    try:
        root = value.resolve(strict=True)
    except OSError as exc:
        raise DocumentationError(f"repository path is unavailable: {value}: {exc}") from exc
    result = subprocess.run(
        ["git", "-C", str(root), "rev-parse", "--show-toplevel"],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "no diagnostic"
        raise DocumentationError(f"not a Git worktree: {root}: {detail}")
    actual = Path(result.stdout.strip()).resolve()
    if actual != root:
        raise DocumentationError(f"repository path is not the worktree root: {root}")
    return root


def anchors(document: Path) -> set[str]:
    """Return the GitHub-style anchors generated by one Markdown document."""
    counts: dict[str, int] = {}
    result: set[str] = set()
    for line in document.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^#{1,6}\s+(.+?)\s*#*\s*$", line)
        if not match:
            continue
        heading = re.sub(r"<[^>]*>", "", match.group(1)).lower()
        base = re.sub(r"[^\w\- ]", "", heading).replace(" ", "-")
        number = counts.get(base, 0)
        counts[base] = number + 1
        result.add(base if number == 0 else f"{base}-{number}")
    return result


def validate_links(
    root: Path,
    documents: Iterable[Path],
    problems: list[str],
) -> dict[Path, set[Path]]:
    """Validate local Markdown links and collect inbound references."""
    document_list = list(documents)
    document_anchors = {document: anchors(document) for document in document_list}
    inbound: dict[Path, set[Path]] = {}
    for document in document_list:
        text = document.read_text(encoding="utf-8")
        for raw_target in re.findall(r"\[[^\]]+\]\(([^)]+)\)", text):
            raw_target = raw_target.strip().strip("<>")
            if raw_target.startswith(EXTERNAL_SCHEMES):
                continue
            path_text, separator, fragment = raw_target.partition("#")
            path = (
                document
                if not path_text
                else (document.parent / unquote(path_text)).resolve()
            )
            if not path.exists():
                problems.append(
                    f"missing link: {document.relative_to(root)} -> {raw_target}"
                )
                continue
            inbound.setdefault(path, set()).add(document)
            if separator and path.suffix == ".md":
                fragment = unquote(fragment).lower()
                if fragment not in document_anchors.get(path, set()):
                    problems.append(
                        f"missing anchor: {document.relative_to(root)} -> {raw_target}"
                    )
    return inbound


def card_section(text: str, heading: str) -> str:
    """Return one level-two card section without its heading."""
    marker = f"## {heading}\n"
    return text.split(marker, 1)[1].split("\n## ", 1)[0].strip()


def validate_cards(root: Path, problems: list[str]) -> dict[str, TaskCard]:
    """Validate task-card structure, links, and direct dependency semantics."""
    task_root = root / "docs" / "tasks"
    required_readmes = {
        task_root / "README.md",
        task_root / "cards" / "README.md",
        task_root / "TODO" / "README.md",
        task_root / "IN_PROGRESS" / "README.md",
        task_root / "INTEGRATION_REVIEW" / "README.md",
        task_root / "COMPLETED" / "README.md",
        task_root / "UNREFINED" / "README.md",
    }
    for readme in sorted(required_readmes):
        if not readme.is_file():
            problems.append(f"missing task-registry README: {readme.relative_to(root)}")

    cards: dict[str, TaskCard] = {}
    proposals: dict[str, Path] = {}
    actionable_sections = frozenset(CARD_SECTIONS) | frozenset(
        STABLE_CARD_SECTIONS
    )
    required_pattern = re.compile(
        r"^- \[([A-Z0-9-]+)\]\([^)]+\.md\) — Required: .+$"
    )
    unblock_pattern = re.compile(
        r"^- \[([A-Z0-9-]+)\]\([^)]+\.md\) — (Fully|Partially): .+$"
    )
    for path in sorted(task_root.rglob("*.md")):
        if path in required_readmes:
            continue
        if path.parent == task_root / "UNREFINED":
            text = path.read_text(encoding="utf-8")
            titles = re.findall(r"^#\s+(.+)$", text, flags=re.MULTILINE)
            title = (
                TASK_H1_PATTERN.fullmatch(titles[0])
                if len(titles) == 1
                else None
            )
            if not title:
                problems.append(f"invalid proposal H1: {path.relative_to(root)}")
                continue
            proposal_id = title.group(1)
            if not path.name.startswith(f"{proposal_id}-"):
                problems.append(
                    f"proposal ID/filename mismatch: {path.relative_to(root)}"
                )
            if proposal_id in proposals or proposal_id in cards:
                problems.append(f"duplicate proposal ID: {proposal_id}")
            proposals[proposal_id] = path

            state_lines = re.findall(r"^State: .+$", text, flags=re.MULTILINE)
            if len(state_lines) != 1 or not UNREFINED_STATE_PATTERN.fullmatch(
                state_lines[0]
            ):
                problems.append(
                    "invalid proposal state declaration: "
                    f"{path.relative_to(root)}"
                )

            headings = re.findall(r"^##\s+(.+)$", text, flags=re.MULTILINE)
            prior_index = -1
            valid_heading_order = True
            for required_heading in UNREFINED_SECTIONS:
                if headings.count(required_heading) != 1:
                    valid_heading_order = False
                    break
                heading_index = headings.index(required_heading)
                if heading_index <= prior_index:
                    valid_heading_order = False
                    break
                prior_index = heading_index
            if not valid_heading_order:
                problems.append(
                    f"proposal heading order/count: {path.relative_to(root)}"
                )

            actionable_heading = next(
                (
                    heading
                    for heading in headings
                    if heading in actionable_sections
                ),
                None,
            )
            if actionable_heading is not None:
                problems.append(
                    "actionable card heading in proposal: "
                    f"{path.relative_to(root)} -> {actionable_heading}"
                )
            if re.search(
                r"^- \[[A-Z0-9-]+\]\([^)]+\.md\) — "
                r"(?:Required|Fully|Partially): .+$",
                text,
                flags=re.MULTILINE,
            ):
                problems.append(
                    f"dependency edge in proposal: {path.relative_to(root)}"
                )
            continue
        stable_schema = path.parent == task_root / "cards"
        legacy_schema = (
            path.parent.name in CARD_STATUSES and path.parent.parent == task_root
        )
        if not stable_schema and not legacy_schema:
            problems.append(f"invalid card location: {path.relative_to(root)}")
            continue
        text = path.read_text(encoding="utf-8")
        titles = re.findall(r"^#\s+(.+)$", text, flags=re.MULTILINE)
        title = (
            TASK_H1_PATTERN.fullmatch(titles[0])
            if len(titles) == 1
            else None
        )
        if not title:
            problems.append(f"invalid card H1: {path.relative_to(root)}")
            continue
        card_id = title.group(1)
        if not path.name.startswith(f"{card_id}-"):
            problems.append(f"card ID/filename mismatch: {path.relative_to(root)}")
        if card_id in cards or card_id in proposals:
            problems.append(f"duplicate card ID: {card_id}")
        headings = re.findall(r"^##\s+(.+)$", text, flags=re.MULTILINE)
        expected_sections = STABLE_CARD_SECTIONS if stable_schema else CARD_SECTIONS
        structurally_valid = headings == list(expected_sections)
        if not structurally_valid:
            problems.append(f"card heading order/count: {path.relative_to(root)}")

        state_lines = re.findall(r"^State: .+$", text, flags=re.MULTILINE)
        state_match = (
            CARD_STATE_PATTERN.fullmatch(state_lines[0])
            if len(state_lines) == 1
            else None
        )
        if stable_schema and state_match is None:
            problems.append(f"invalid card state declaration: {path.relative_to(root)}")
        elif legacy_schema and state_lines and state_match is None:
            problems.append(f"invalid card state declaration: {path.relative_to(root)}")
        explicit_state = state_match is not None
        state = (
            state_match.group(1)
            if state_match is not None
            else (
                "planned"
                if stable_schema
                else LEGACY_STATE_BY_STATUS[path.parent.name]
            )
        )

        blockers: frozenset[str] = frozenset()
        unblocks: dict[str, str] = {}
        if structurally_valid:
            blocked_text = card_section(text, "Blocked by")
            blocked_lines = [
                line for line in blocked_text.splitlines() if line.strip()
            ]
            if blocked_lines != ["- None."] and not all(
                required_pattern.fullmatch(line) for line in blocked_lines
            ):
                problems.append(f"invalid Blocked by syntax: {path.relative_to(root)}")
            blockers = frozenset(
                re.findall(r"\[([A-Z0-9-]+)\]\(", blocked_text)
            )

            if not stable_schema:
                unblocks_text = card_section(text, "Completion unblocks")
                unblock_lines = [
                    line for line in unblocks_text.splitlines() if line.strip()
                ]
                if unblock_lines != ["- None."] and not all(
                    unblock_pattern.fullmatch(line) for line in unblock_lines
                ):
                    problems.append(
                        "invalid Completion unblocks syntax: "
                        f"{path.relative_to(root)}"
                    )
                unblocks = {
                    target: mode
                    for target, mode in re.findall(
                        r"\[([A-Z0-9-]+)\]\([^)]+\) — (Fully|Partially):",
                        unblocks_text,
                    )
                }

            completion_record = card_section(text, "Completion record")
            if state == "completed" and completion_record in {
                "",
                "- None.",
                "None.",
                "Not complete.",
                "Pending.",
                "TBD.",
            }:
                problems.append(
                    f"placeholder completion record: {path.relative_to(root)}"
                )
            if state == "retired" and not (
                re.search(r"(?m)^- Rationale: \S.+$", completion_record)
                and re.search(r"(?m)^- Successor: \S.+$", completion_record)
            ):
                problems.append(
                    "retired card requires rationale and successor: "
                    f"{path.relative_to(root)}"
                )

        cards[card_id] = TaskCard(
            card_id=card_id,
            path=path,
            state=state,
            explicit_state=explicit_state,
            stable_schema=stable_schema,
            blockers=blockers,
            unblocks=unblocks,
        )

        card_links = re.findall(
            r"\[([A-Z0-9-]+)\]\(([^)]+\.md)\)", text
        )
        for label, target in card_links:
            resolved = (path.parent / target).resolve()
            if resolved.parent.parent == task_root and not resolved.name.startswith(
                f"{label}-"
            ):
                problems.append(
                    f"card-link label/target mismatch: {path.relative_to(root)} "
                    f"{label} -> {target}"
                )

    for target, card in cards.items():
        for source in card.blockers:
            if source not in cards:
                problems.append(f"unknown blocker: {target} <- {source}")
            elif not card.stable_schema and target not in cards[source].unblocks:
                problems.append(f"missing reciprocal unblock: {source} -> {target}")
            if source == target:
                problems.append(f"self dependency: {target}")
    for source, card in cards.items():
        for target, mode in card.unblocks.items():
            if target not in cards:
                problems.append(f"unknown unblock target: {source} -> {target}")
            elif mode == "Fully" and cards[target].blockers != {source}:
                problems.append(f"invalid Fully relationship: {source} -> {target}")

    visiting: list[str] = []
    visited: set[str] = set()

    def visit(card_id: str) -> None:
        if card_id in visiting:
            problems.append("dependency cycle: " + " -> ".join(visiting + [card_id]))
            return
        if card_id in visited:
            return
        visiting.append(card_id)
        for dependency in cards[card_id].blockers:
            if dependency in cards:
                visit(dependency)
        visiting.pop()
        visited.add(card_id)

    for card_id in cards:
        visit(card_id)

    for card_id, card in cards.items():
        legacy_started = (
            not card.explicit_state
            and not card.stable_schema
            and card.path.parent.name in STARTED_CARD_STATUSES
        )
        if card.state in {"review", "completed"} or legacy_started:
            for dependency in card.blockers:
                if dependency in cards and cards[dependency].state != "completed":
                    problems.append(
                        "active/completed card has incomplete blocker: "
                        f"{card_id} <- {dependency}"
                    )
    return cards


def validate_diagrams(
    root: Path,
    diagrams: Iterable[Path],
    inbound: dict[Path, set[Path]],
    problems: list[str],
) -> int:
    """Validate Mermaid source shape and inbound references."""
    diagram_list = list(diagrams)
    for diagram in diagram_list:
        text = diagram.read_text(encoding="utf-8")
        meaningful = [line.strip() for line in text.splitlines() if line.strip()]
        if not meaningful or not re.fullmatch(
            r"flowchart (LR|RL|TB|BT|TD)", meaningful[0]
        ):
            problems.append(f"invalid Mermaid declaration: {diagram.relative_to(root)}")
        if "```" in text:
            problems.append(f"Markdown fence in Mermaid source: {diagram.relative_to(root)}")
        if not (inbound.get(diagram, set()) - {diagram}):
            problems.append(f"orphan Mermaid source: {diagram.relative_to(root)}")
    return len(diagram_list)


def validate(root: Path) -> tuple[int, int, int]:
    """Run the complete structural documentation gate."""
    documents = git_paths(root, "*.md")
    diagrams = git_paths(root, "*.mmd")
    problems: list[str] = []
    inbound = validate_links(root, documents, problems)
    cards = validate_cards(root, problems)
    diagram_count = validate_diagrams(root, diagrams, inbound, problems)
    if problems:
        raise DocumentationError("Documentation gate failures:\n" + "\n".join(problems))
    return len(documents), len(cards), diagram_count


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate NORAD documentation links, task cards, and diagrams."
    )
    parser.add_argument(
        "--repo",
        required=True,
        type=Path,
        help="exact Git worktree root to validate",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    try:
        root = repository_root(args.repo)
        document_count, card_count, diagram_count = validate(root)
    except DocumentationError as exc:
        raise SystemExit(f"ERROR: {exc}") from exc
    print(
        f"PASS documentation structure ({document_count} Markdown documents, "
        f"{card_count} task cards, {diagram_count} Mermaid sources)"
    )


if __name__ == "__main__":
    main()
